// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	CredentialsRequest
	AuthenticateResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type CredentialsRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *CredentialsRequest) Reset()                    { *m = CredentialsRequest{} }
func (m *CredentialsRequest) String() string            { return proto1.CompactTextString(m) }
func (*CredentialsRequest) ProtoMessage()               {}
func (*CredentialsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CredentialsRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CredentialsRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateResponse struct {
	Authenticated bool  `protobuf:"varint,1,opt,name=authenticated" json:"authenticated,omitempty"`
	Status        int32 `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
}

func (m *AuthenticateResponse) Reset()                    { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string            { return proto1.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()               {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthenticateResponse) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func (m *AuthenticateResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto1.RegisterType((*CredentialsRequest)(nil), "proto.CredentialsRequest")
	proto1.RegisterType((*AuthenticateResponse)(nil), "proto.AuthenticateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PasswordAuthenticator service

type PasswordAuthenticatorClient interface {
	Authenticate(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
}

type passwordAuthenticatorClient struct {
	cc *grpc.ClientConn
}

func NewPasswordAuthenticatorClient(cc *grpc.ClientConn) PasswordAuthenticatorClient {
	return &passwordAuthenticatorClient{cc}
}

func (c *passwordAuthenticatorClient) Authenticate(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := grpc.Invoke(ctx, "/proto.PasswordAuthenticator/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PasswordAuthenticator service

type PasswordAuthenticatorServer interface {
	Authenticate(context.Context, *CredentialsRequest) (*AuthenticateResponse, error)
}

func RegisterPasswordAuthenticatorServer(s *grpc.Server, srv PasswordAuthenticatorServer) {
	s.RegisterService(&_PasswordAuthenticator_serviceDesc, srv)
}

func _PasswordAuthenticator_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordAuthenticatorServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PasswordAuthenticator/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordAuthenticatorServer).Authenticate(ctx, req.(*CredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PasswordAuthenticator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PasswordAuthenticator",
	HandlerType: (*PasswordAuthenticatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _PasswordAuthenticator_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

func init() { proto1.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x3e, 0x5c, 0x42, 0xce, 0x45,
	0xa9, 0x29, 0xa9, 0x79, 0x25, 0x99, 0x89, 0x39, 0xc5, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25,
	0x42, 0x52, 0x5c, 0x1c, 0xa5, 0xc5, 0xa9, 0x45, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x70, 0x3e, 0x48, 0xae, 0x20, 0xb1, 0xb8, 0xb8, 0x3c, 0xbf, 0x28, 0x45, 0x82,
	0x09, 0x22, 0x07, 0xe3, 0x2b, 0x85, 0x70, 0x89, 0x38, 0x96, 0x96, 0x64, 0x80, 0x4c, 0x4b, 0x4e,
	0x2c, 0x49, 0x0d, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x52, 0xe1, 0xe2, 0x4d, 0x44,
	0x12, 0x4f, 0x01, 0x1b, 0xca, 0x11, 0x84, 0x2a, 0x28, 0x24, 0xc6, 0xc5, 0x56, 0x5c, 0x92, 0x58,
	0x52, 0x5a, 0x0c, 0x36, 0x97, 0x35, 0x08, 0xca, 0x33, 0x8a, 0xe7, 0x12, 0x0d, 0x80, 0xda, 0x80,
	0x64, 0x7a, 0x7e, 0x91, 0x90, 0x1b, 0x17, 0x0f, 0xb2, 0x75, 0x42, 0x92, 0x10, 0xbf, 0xe9, 0x61,
	0xfa, 0x48, 0x4a, 0x1a, 0x2a, 0x85, 0xcd, 0x79, 0x49, 0x6c, 0x60, 0x39, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x87, 0xdc, 0x40, 0x61, 0x20, 0x01, 0x00, 0x00,
}
