// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token-provider.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:

	token-provider.proto

It has these top-level messages:

	TokenRequest
	TokenResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type TokenRequest struct {
	Params []string `protobuf:"bytes,1,rep,name=params" json:"params,omitempty"`
}

func (m *TokenRequest) Reset()                    { *m = TokenRequest{} }
func (m *TokenRequest) String() string            { return proto1.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()               {}
func (*TokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TokenRequest) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type TokenResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Status  int32  `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	Token   string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *TokenResponse) Reset()                    { *m = TokenResponse{} }
func (m *TokenResponse) String() string            { return proto1.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()               {}
func (*TokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TokenResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TokenResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto1.RegisterType((*TokenRequest)(nil), "proto.TokenRequest")
	proto1.RegisterType((*TokenResponse)(nil), "proto.TokenResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TokenProvider service

type TokenProviderClient interface {
	GetToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
}

type tokenProviderClient struct {
	cc *grpc.ClientConn
}

func NewTokenProviderClient(cc *grpc.ClientConn) TokenProviderClient {
	return &tokenProviderClient{cc}
}

func (c *tokenProviderClient) GetToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := grpc.Invoke(ctx, "/proto.TokenProvider/GetToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TokenProvider service

type TokenProviderServer interface {
	GetToken(context.Context, *TokenRequest) (*TokenResponse, error)
}

func RegisterTokenProviderServer(s *grpc.Server, srv TokenProviderServer) {
	s.RegisterService(&_TokenProvider_serviceDesc, srv)
}

func _TokenProvider_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenProviderServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TokenProvider/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenProviderServer).GetToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TokenProvider",
	HandlerType: (*TokenProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _TokenProvider_GetToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "token-provider.proto",
}

func init() { proto1.RegisterFile("token-provider.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0x31, 0x0b, 0xc2, 0x30,
	0x10, 0x85, 0x89, 0xa5, 0xb5, 0x3d, 0x74, 0x89, 0x45, 0x82, 0x53, 0xe9, 0x20, 0x59, 0xec, 0xa0,
	0xf8, 0x17, 0x74, 0x95, 0x20, 0x38, 0xd7, 0x7a, 0x83, 0x88, 0x4d, 0xcc, 0xa5, 0xfe, 0x7e, 0x69,
	0x12, 0x41, 0xa7, 0xe3, 0x7b, 0xf7, 0x78, 0x7c, 0x50, 0x3a, 0xfd, 0xc0, 0x7e, 0x63, 0xac, 0x7e,
	0xdf, 0x6f, 0x68, 0x1b, 0x63, 0xb5, 0xd3, 0x3c, 0xf5, 0xa7, 0x5e, 0xc3, 0xec, 0x3c, 0xbe, 0x15,
	0xbe, 0x06, 0x24, 0xc7, 0x97, 0x90, 0x99, 0xd6, 0xb6, 0x4f, 0x12, 0xac, 0x4a, 0x64, 0xa1, 0x22,
	0xd5, 0x17, 0x98, 0xc7, 0x1e, 0x19, 0xdd, 0x13, 0x72, 0x01, 0x53, 0x1a, 0xba, 0x0e, 0x69, 0x6c,
	0x32, 0x99, 0xab, 0x2f, 0x8e, 0x13, 0xe4, 0x5a, 0x37, 0x90, 0x98, 0x54, 0x4c, 0xa6, 0x2a, 0x12,
	0x2f, 0x21, 0xf5, 0x26, 0x22, 0xa9, 0x98, 0x2c, 0x54, 0x80, 0xed, 0x21, 0x0e, 0x9f, 0xa2, 0x1e,
	0xdf, 0x43, 0x7e, 0x44, 0xe7, 0x33, 0xbe, 0x08, 0xb2, 0xcd, 0xaf, 0xe2, 0xaa, 0xfc, 0x0f, 0x83,
	0xcf, 0x35, 0xf3, 0xe1, 0xee, 0x13, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xe1, 0x96, 0xe0, 0xee, 0x00,
	0x00, 0x00,
}
