name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get git describe
        id: get-version
        run: |
          describe=$(git describe --tags --always --dirty)
          echo "GIT_COMMIT_REF_NAME=$describe" >> $GITHUB_ENV
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - run: go version
      - name: Run build and test
        run: make clean build test clean
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            grepplabs/kafka-proxy
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Docker meta - all
        id: meta-all
        uses: docker/metadata-action@v4
        with:
          images: |
            grepplabs/kafka-proxy
          flavor: |
            suffix=-all
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VERSION=${{ env.GIT_COMMIT_REF_NAME }}
      - name: Docker build and push - all
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile.all
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-all.outputs.tags }}
          labels: ${{ steps.meta-all.outputs.labels }}
          build-args: VERSION=${{ env.GIT_COMMIT_REF_NAME }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
